spring:
  application:
    name: WikiApp
  datasource:
    url: jdbc:postgresql://localhost:5432/wikiapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  profiles:
    active: development

server:
  port: 8081

logging:
  level:
    root: INFO
    ru.altacod: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true